<a href="https://colab.research.google.com/github/bhavishya-boost/Data-Science-Visualization-Lab-Experiment-/blob/main/Pandas_DataFrames_Lab_Practice_Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

SECTION : **A**

In [ ]:
#1
student_dict = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],'Age': [20, 21, 19, 22],'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}
student_df = pd.DataFrame(student_dict)

In [ ]:
#2
print(student_df)

      Name  Age         City
0    Alice   20     New York
1      Bob   21  Los Angeles
2  Charlie   19      Chicago
3    David   22      Houston

In [ ]:
#3
print(student_df.columns.tolist())

['Name', 'Age', 'City']

In [ ]:
#4
student_df['Name']

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [ ]:
#5
student_df['City']

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: City, dtype: object

In [ ]:
#6
name_city_df = student_df[['Name', 'City']]
print(name_city_df)

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [ ]:
#7
book_dict = {'Book': ['1984', 'To Kill a Mockingbird', 'The Great Gatsby'],'Author': ['George Orwell', 'Harper Lee', 'F. Scott Fitzgerald'],'Price': [15.99, 12.50, 10.99]}
book_df = pd.DataFrame(book_dict)
book_df

                    Book               Author  Price
0                   1984        George Orwell  15.99
1  To Kill a Mockingbird           Harper Lee  12.50
2       The Great Gatsby  F. Scott Fitzgerald  10.99

In [ ]:
#8
book_df['Publisher'] = 'Penguin Books'
book_df

                    Book               Author  Price      Publisher
0                   1984        George Orwell  15.99  Penguin Books
1  To Kill a Mockingbird           Harper Lee  12.50  Penguin Books
2       The Great Gatsby  F. Scott Fitzgerald  10.99  Penguin Books

In [ ]:
#9
df = pd.DataFrame({'Item': ['A', 'B', 'C', 'D', 'E']})
df['SerialNo'] = np.arange(5)
df

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

In [ ]:
#10
del df['SerialNo']
df

  Item
0    A
1    B
2    C
3    D
4    E

In [ ]:
#11
movie_df = pd.DataFrame({'Movie': ['Inception', 'The Dark Knight', 'Pulp Fiction'], 'Year': [2020,2025,2026] , 'Rating': [8.8, 9.0, 8.9]})
movie_df

             Movie  Year  Rating
0        Inception  2020     8.8
1  The Dark Knight  2025     9.0
2     Pulp Fiction  2026     8.9

In [ ]:
#12
movie_2df = pd.DataFrame(movie_df, columns=['Movie', 'Rating', 'Director'])
movie_2df

             Movie  Rating  Director
0        Inception     8.8       NaN
1  The Dark Knight     9.0       NaN
2     Pulp Fiction     8.9       NaN

In [ ]:
#13
city = pd.Series(['Miami', 'Seattle'], index=[0, 3])
city

0      Miami
3    Seattle
dtype: object

In [ ]:
#14
df = pd.DataFrame({'ID': [101, 102, 103, 104]})
df['Branch'] = city
df

    ID   Branch
0  101    Miami
1  102      NaN
2  103      NaN
3  104  Seattle

SECTION : **B**

In [ ]:
#15
#doubt

In [ ]:
#16
employee_df = pd.DataFrame({'Employee': ['E1', 'E2', 'E3', 'E4', 'E5'],'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],'Experience': [2, 5, 3, 8, 1]})
emp_sub_df = employee_df[['Employee', 'Experience']]
emp_sub_df

  Employee  Experience
0       E1           2
1       E2           5
2       E3           3
3       E4           8
4       E5           1

In [ ]:
#17
dept_col = employee_df['Department']
print("Department Column:\n", dept_col)
print("\nAll Column Names:", employee_df.columns)

Department Column:
 0         HR
1         IT
2    Finance
3         IT
4         HR
Name: Department, dtype: object

All Column Names: Index(['Employee', 'Department', 'Experience'], dtype='object')

In [ ]:
#18
employee_df['Office'] = 'Head Office'
employee_df

  Employee Department  Experience       Office
0       E1         HR           2  Head Office
1       E2         IT           5  Head Office
2       E3    Finance           3  Head Office
3       E4         IT           8  Head Office
4       E5         HR           1  Head Office

In [ ]:
#19
employee_df['Office'] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0       E1         HR           2       0
1       E2         IT           5       1
2       E3    Finance           3       2
3       E4         IT           8       3
4       E5         HR           1       4

In [ ]:
#20
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0       E1         HR           2   Delhi
1       E2         IT           5     NaN
2       E3    Finance           3  Mumbai
3       E4         IT           8     NaN
4       E5         HR           1    Pune

In [ ]:
#21
del employee_df['Office']
employee_df

  Employee Department  Experience
0       E1         HR           2
1       E2         IT           5
2       E3    Finance           3
3       E4         IT           8
4       E5         HR           1

In [ ]:
#22
product_df = pd.DataFrame({'Product': ['Laptop', 'Phone', 'Tablet'],'Category': ['Electronics', 'Electronics', 'Electronics'],'Price': [50000, 30000, 20000]})
reordered_product_df = pd.DataFrame(product_df, columns=['Price', 'Product', 'Category'])
reordered_product_df

   Price Product     Category
0  50000  Laptop  Electronics
1  30000   Phone  Electronics
2  20000  Tablet  Electronics

In [ ]:
#23
source_data = {'A': [1, 2], 'B': [3, 4], 'C': [5, 6]}
df_missing_col = pd.DataFrame(source_data, columns=['A', 'B', 'C', 'MissingCol'])
df_missing_col

   A  B  C MissingCol
0  1  3  5        NaN
1  2  4  6        NaN

In [ ]:
#24
space_df = pd.DataFrame({'Student Name': ['Aman', 'Priya'],'Total Marks': [85, 92]})
marks = space_df['Total Marks']
marks

0    85
1    92
Name: Total Marks, dtype: int64

In [ ]:
#25
clip_df = pd.read_clipboard()
print("Column names:", clip_df.columns)
selected_cols_df = clip_df.iloc[:, :3]
selected_cols_df

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

SECTION : **C**

In [ ]:
#26
course_df = pd.DataFrame({'Student': ['A', 'B', 'C', 'D', 'E'],'Course': ['CSE', 'ECE', 'CSE', 'ME', 'ECE'],'Score': [88, 76, 90, 65, 82]})
print("Columns:", course_df.columns)
print("\nStudent Column:\n", course_df['Student'])
student_score_df = course_df[['Student', 'Score']]
print("\nStudent and Score DF:\n", student_score_df)
course_df['Batch'] = '2026'
print("\nUpdated course_df:\n", course_df)

Columns: Index(['Student', 'Course', 'Score'], dtype='object')

Student Column:
 0    A
1    B
2    C
3    D
4    E
Name: Student, dtype: object

Student and Score DF:
   Student  Score
0       A     88
1       B     76
2       C     90
3       D     65
4       E     82

Updated course_df:
   Student Course  Score Batch
0       A    CSE     88  2026
1       B    ECE     76  2026
2       C    CSE     90  2026
3       D     ME     65  2026
4       E    ECE     82  2026

In [ ]:
#27
travel_df = pd.DataFrame({'City': ['Delhi', 'Agra', 'Jaipur', 'Lucknow', 'Kanpur']})
travel_df['Code'] = np.arange(5)
print("After adding Code column:\n", travel_df)
code_series = pd.Series([101, 104], index=[1, 4])
travel_df['Code'] = code_series
print("\nAfter replacing Code column with indexed Series:\n", travel_df)

After adding Code column:
       City  Code
0    Delhi     0
1     Agra     1
2   Jaipur     2
3  Lucknow     3
4   Kanpur     4

After replacing Code column with indexed Series:
       City   Code
0    Delhi    NaN
1     Agra  101.0
2   Jaipur    NaN
3  Lucknow    NaN
4   Kanpur  104.0

In [ ]:
#28
school_df = pd.DataFrame({'Student': ['Rohan', 'Soham', 'Reena'],'Class': [10, 10, 10],'Section': ['A', 'B', 'A']})
school_df2 = pd.DataFrame(school_df, columns=['Student', 'Class', 'Section', 'House'])
print("Before assigning House value:\n", school_df2)
school_df2['House'] = 'Red'
print("\nAfter assigning House value:\n", school_df2)

Before assigning House value:
   Student  Class Section  House
0   Rohan     10       A    NaN
1   Soham     10       B    NaN
2   Reena     10       A    NaN

After assigning House value:
   Student  Class Section House
0   Rohan     10       A   Red
1   Soham     10       B   Red
2   Reena     10       A   Red

In [ ]:
#29
item_list = ['Pen', 'Pencil', 'Notebook', 'Eraser']
qty_list = [10, 20, 15, 30]
inventory_df = pd.DataFrame({'Item': item_list, 'Quantity': qty_list})
discount_series = pd.Series([5, 10], index=[0, 2])
inventory_df['Discount'] = discount_series
print("After adding Discount column:\n", inventory_df)
del inventory_df['Discount']
print("\nAfter deleting Discount column:\n", inventory_df)

After adding Discount column:
        Item  Quantity  Discount
0       Pen        10       5.0
1    Pencil        20       NaN
2  Notebook        15      10.0
3    Eraser        30       NaN

After deleting Discount column:
        Item  Quantity
0       Pen        10
1    Pencil        20
2  Notebook        15
3    Eraser        30

In [ ]:
#30
lab_df = pd.read_clipboard()
print("1. Full DataFrame:\n", lab_df)
print("\n2. Column Names:\n", lab_df.columns)
single_word_col_name = [c for c in lab_df.columns if " " not in c][0]
print(f"\n3. Single-word column ({single_word_col_name}):\n", lab_df[single_word_col_name])
space_col_name = [c for c in lab_df.columns if " " in c][0]
print(f"\n4. Column with space ({space_col_name}):\n", lab_df[space_col_name])
small_df = lab_df[[single_word_col_name, space_col_name]]
print("\n5. Smaller DataFrame:\n", small_df)
lab_df['Status'] = 'Active'
print("\n6. DataFrame after adding Status column:\n", lab_df)
del lab_df['Status']
print("\n7. Final DataFrame after deleting Status column:\n", lab_df)

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error